stages:
  - build
  - setup
  - test
  - deploy
  

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags
    
setup:
  stage: setup
  script:
    - npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test
    - ./gradlew sonarqube

jest:
  stage: test
  script:
    - cd client
    - npm install jest-sonar-reporter
    - npm run unit
    - npm run sonarqube
    

dev-build:
  stage: deploy
  script:
#   - touch /home/gitlab-runner/set-env-vars.txt
#   - chmod a+rwx /home/gitlab-runner/set-env-vars.txt
    - source /home/gitlab-runner/set-env-vars.txt
    - fuser -k 9499/tcp 9500/tcp || true
    - cd client
    - npm run build
    - rm -rf /home/gitlab-runner/test-client/
    - mkdir -p /home/gitlab-runner/test-client/
    - cp -r ./dist /home/gitlab-runner/test-client
    - cd ../server
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/test-server/
    - mkdir -p /home/gitlab-runner/test-server/
    - cp -r ./build/libs /home/gitlab-runner/test-server
    #update scripts and restart service vvv
    - rm -f /home/gitlab-runner/runTestClient.sh || true
    - cp ../bashscripts/runTestClient.sh /home/gitlab-runner/runTestClient.sh
    - sudo systemctl restart testClient
    - rm -f /home/gitlab-runner/runTestServer.sh || true
    - cp ../bashscripts/runTestServer.sh /home/gitlab-runner/runTestServer.sh
    - sudo systemctl restart testServer
  only:
    refs:
      - development



release-build:
  stage: deploy
  script:
    - source /home/gitlab-runner/set-env-vars.txt
    - fuser -k 8999/tcp 9000/tcp || true
    - cd client
    - npm run build-prod
    - cd ../server
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/prod-server/
    - mkdir -p /home/gitlab-runner/prod-server/
    - cp -r ./build/libs /home/gitlab-runner/prod-server
    - rm -rf /home/gitlab-runner/prod-client/
    - mkdir -p /home/gitlab-runner/prod-client/
    - cp -r ./dist /home/gitlab-runner/prod-client
    #update scripts and restart service vvv
    - rm -f /home/gitlab-runner/runProdServer.sh || true
    - cp ../bashscripts/runProdServer.sh /home/gitlab-runner/runProdServer.sh
    - sudo systemctl restart prodServer
    - rm -f /home/gitlab-runner/runProdClient.sh || true
    - cp ../bashscripts/runProdClient.sh /home/gitlab-runner/runProdClient.sh
    - sudo systemctl restart prodClient
  artifacts:
    paths:
      - client/dist
      - server/out
  only:
    - tags
