stages:
  - build
  - setup
  - test
  - deploy
  

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags
    
setup:
  stage: setup
  script:
    - npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test
    - ./gradlew sonarqube

jest:
  stage: test
  script:
    - cd client
    - npm install jest-sonar-reporter
    - npm run unit
    - npm run sonarqube
    

dev-build:
  stage: deploy
  script:
    - fuser -k 9499/tcp 9500/tcp || true
    - cd client
    - npm run build
    - rm -rf /home/gitlab-runner/test-client/
    - mkdir -p /home/gitlab-runner/test-client/
    - cp -r ./dist /home/gitlab-runner/test-client
    - cd ../server
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/test-server/
    - mkdir -p /home/gitlab-runner/test-server/
    - cp -r ./build/libs /home/gitlab-runner/test-server
#old block
#    - mkdir -p ../client-dev/
#    - mkdir -p ../server-dev/
#    - cp -r ./client/dist/ ../client-dev/
#    - cp -r ./server/build/libs ../server-dev
#    - screen -d -m serve -s ../client-dev/dist -l 9500 # convert to be run with service
#    - screen -d -m java -jar ../server-dev/libs/server-0.0.1-SNAPSHOT.jar --server.port=9499 # convert to be run with service
    #update scripts and restart service vvv
    - rm -f /home/gitlab-runner/runTestServer.sh || true
    - cp ../bashscripts/runTestServer.sh /home/gitlab-runner/runTestServer.sh
    - sudo systemctl restart testServer
    - rm -f /home/gitlab-runner/runTestClient.sh || true
    - cp ../bashscripts/runTestClient.sh /home/gitlab-runner/runTestClient.sh
    - sudo systemctl restart testClient
    - journalctl
#  only:
#    refs:
#      - development



release-build:
  stage: deploy
  script:
    - fuser -k 8999/tcp 9000/tcp || true
    - cd client
    - npm run build-prod
    - cd ../server
    - ./gradlew bootJar
#old block
#    - cd ..
#    - mkdir -p ../client-prod/
#    - mkdir -p ../server-prod/
#    - cp -r ./client/dist/ ../client-prod/
#    - cp -r ./server/build/libs ../server-prod/
    #- java -jar ../server-prod/libs/server-0.0.1-SNAPSHOT.jar --server.port=8999 # convert to be run with service
    #- serve -s ../client-prod/dist -l 9000 # convert to be run with service
    - rm -rf /home/gitlab-runner/prod-server/
    - mkdir -p /home/gitlab-runner/prod-server/
    - cp -r ./build/libs /home/gitlab-runner/prod-server
    - rm -rf /home/gitlab-runner/prod-client/
    - mkdir -p /home/gitlab-runner/prod-client/
    - cp -r ./dist /home/gitlab-runner/prod-client
    - rm -f /home/gitlab-runner/runProdServer.sh || true
    - cp ../bashscripts/runProdServer.sh /home/gitlab-runner/runProdServer.sh
    - sudo systemctl restart prodServer
    - rm -f /home/gitlab-runner/runProdClient.sh || true
    - cp ../bashscripts/runProdClient.sh /home/gitlab-runner/runProdClient.sh
    - sudo systemctl restart prodClient
  artifacts:
    paths:
      - client/dist
      - server/out
  only:
    - tags
